# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cc8962c5b8c53eae44bd477c33383ccd5e67c55b48435bd66a5493e3ba8a5f2fe79b82d7b785e910f38f731802cbfedc5cc81c9a3f8a37cbbdd6d69a090333c6

test:
  secret_key_base: da7099143e70ffe1b4fb6bdd3c0c45af6b4c4b7ec917adf3a736da02161658a501738909ffc4cc9413cd8e9788f6657370a6b16ff0cafa937c91f7d80ffa9edc

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
